//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsForCoders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public Entreprise()
        {
            this.Offres = new HashSet<Offre>();
            this.Candidats = new HashSet<Candidat>();
        }
    
        public int EntrepriseID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Cellphone { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<Offre> Offres { get; set; }
        public virtual ICollection<Candidat> Candidats { get; set; }
    }
}
