//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsForCoders.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobsforcodersEntities : DbContext
    {
        public jobsforcodersEntities()
            : base("name=jobsforcodersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Entreprise> Entreprises { get; set; }
        public DbSet<Offre> Offres { get; set; }
        public DbSet<Candidat> Candidats { get; set; }
        public DbSet<Application> Applications { get; set; }
    }
}
